//
//  EnglishPhysicalWordStore.swift
//  Hassouseisei_ver_2_0
//
//  Created by 岡大輔 on 2015/07/05.
//  Copyright (c) 2015年 岡大輔. All rights reserved.
//

import UIKit

class EnglishBusinessWordStore: WordStore {
    override func returnCaption() -> String{
        return "Business Word"
    }
    
    override func ReturningWordArray() -> Array<String>{
        var ReturnWordArray:[String] = []
        
        //http://ejje.weblio.jp/category/business/a
        
        var wordStore = ["a book of contracts","a director-employee","a domestic corporation","a non-permanent resident","a non-resident","a parent company","Ａ type Ｖ beltings",
            "a very prudent fiduciary decision","A&H","A&H model","A&H model law","A&I","A&S","A. M. Best Company","A.S.T.M. colorimeters for petroleum products","A/C",
            "A1949-52 Tables for Assured Lives","AA","AAA","AABD","AABF","AAHA","AAHP","AAI","AAII","AAIM","AAL","AALCO","AALTCI","AALU","AAMGA","Aaphalt concrete","AAPPO",
            "AARP","AATIC","ABA","Abaca","Abacuses","Abalones","Abandoned","abandonment","abatement","Abdominal belts","Abdominal corsets","Abdominal pads","Abdominal ultrasound imaging equipment",
            "Abemaki bark","ABHC","ABI","ABIA","ABIC","Abies oil","ability development","ability to pay principle","ability-based personnel management","ability-based personnel transfer",
            "ABMT","abnormality","ABO","abortion","Abrading instruments","Abrasion","Abrasion resistant hoses","Abrasion testing machines","Abrasive basic products, natural and artificially manufactured",
            "Abrasive cements","Abrasive cloth","Abrasive cloth belts","Abrasive cloth discs","Abrasive cloth rolls","Abrasive cloth sheets","Abrasive cloths","Abrasive combination belts",
            "Abrasive combination discs","Abrasive combination rolls","Abrasive combination sheets","Abrasive combinations","Abrasive compounds for technical purpose","Abrasive cutting machines",
            "Abrasive fibre belts","Abrasive fibre discs","Abrasive fibre rolls","Abrasive fibre sheets","Abrasive fibres","Abrasive pads for kitchen purposes","Abrasive paper",
            "Abrasive pater belts","Abrasive pater discs","Abrasive pater rolls","Abrasive pater sheets","Abrasive paters","Abrasive roller type rice whitening machines",
            "Abrasive roller type/ friction type rice whitening machines","Abrasive sponges for scrubbing the skin","Abrasives","abridged life table","ABS","absence","absence without notice",
            "absenteeism","absenteeism rate","Absolute alcohol","absolute assignment","absolute beneficiary","absolute designation","absolute merit rating","Absorbable surgical sutures",
            "Absorbent cotton","Absorbent cottons","Absorbent gauzes","Absorbent paper for tobacco pipes","Absorbent wadding","Absorber sets","Absorption spectrophotometric analyzers",
            "Absorption type","Absorption type refrigerating machines","Absorptives","abstainee","abstainer","abstention requirement","abstentionist","abstinence","abstinency",
            "abuse","Ac","AC","AC adapters","AC generators","AC motors","AC servomotors","AC small motors","AC watt-hour meters","AC-DC transducers","ACA","Acacia","Acacia trees",
            "academic insurance researcher","academic risk and insurance researcher","Academies","Academy of Life Underwriting","Academy of Producer Insurance Studies",
            "Acaricides","ACAS","ACB","acc","accelerated accrual","accelerated benefit","accelerated benefit option","accelerated benefit plan","accelerated benefit provision",
            "accelerated benefit provisions","accelerated benefits","accelerated benefits option","accelerated benefits plan","accelerated benefits provision","accelerated benefits provisions",
            "accelerated cash benefits","accelerated cost recovery system","accelerated death benefit","accelerated death benefit option","accelerated death benefit plan",
            "accelerated death benefit provision","accelerated death benefit provisions","accelerated death benefits","accelerated death benefits option","accelerated death benefits plan",
            "accelerated death benefits provision","accelerated death benefits provisions","accelerated depreciation","accelerated endowment","accelerated endowment plan",
            "Accelerated License Evaluation Review Techniques","accelerated paid-up","accelerated paid-up plan","accelerated payment of death benefits","accelerated, pre-death benefit option",
            "accelerating benefit option","accelerating benefits option","accelerating death benefit option","accelerating death benefits option","acceleration","acceleration benefit option",
            "acceleration benefits option","acceleration clause","acceleration death benefit option","acceleration death benefits option","acceleration-of-benefit provision",
            "acceleration-of-benefit provisions","acceleration-of-benefits provision","acceleration-of-benefits provisions","accelerative endowment","accelerative endowment plan",
            "accelerative paid-up","accelerative paid-up plan","Accelerometers","accept foreign workers","acceptance","accepting company","accepting house","accepting house committee",
            "access","Access and Benefit Sharing","Access to Medical Reports Act","accessibility of medical care","accession rate","Accessories","Accessories and components of metal working machinery",
            "Accessories and parts for audio and video frequency equipment","Accessories and parts for public address systems","Accessories and parts of compound sanitary equipment",
            "Accessories and parts of motion picture projection equipment","Accessories for absorption spectrophotometric analyzers","Accessories for camera equipment",
            "Accessories for closed circuit television","Accessories for electrical titrators","Accessories for electrode type concentration measuring instruments",
            "Accessories for electrolytic analyzers and coulometric analyzers","Accessories for electron applied analyzers","Accessories for emission spectrophotometric analyzers",
            "Accessories for endoscopes","Accessories for gas chromatographs","Accessories for liquid chromatographs","Accessories for magnetic resonance instruments",
            "Accessories for mass spectrometers","Accessories for microphone equipment","Accessories for microscope apparatus,n.e.c.","Accessories for microscopes",
            "Accessories for motion picture cameras","Accessories for photoelectric photometers and colorimeter","Accessories for polarimetric analyzers","Accessories for polarographs",
            "Accessories for secondary photon process spectrophotometers","Accessories for specific conductivity meters","Accessories for still camera","accessories for thermal analyzers",
            "Accessories for thermal measuring instruments","Accessories for twin layer chromatographs","Accessories for X-ray analyzers","Accessories of containers",
            "Accessories of electricity meters","Accessories of explosives","Accessories of fasteners","Accessories of Japanese clothings","Accessories of Japanese clothings, n.e.c.",
            "Accessories of launcher","Accessories of low frequency electric therapy equipment","Accessories of motion picture sound recording equipment",
            "Accessories of precision measuring machines and instruments","Accessories of samll arms ammunition","Accessories of shell","Accessories used for bearing","Accessories, n.e.c.",
            "Accessory brush for machine","accident","accident and health benefit","accident and health insurance","accident and health line","accident and sickness insurance",
            "accident frequency rate","accident hazard","accident insurance","Accident insurance underwriting","accident prevention advisory committee","accident severity rate",
            "accidental death","accidental death benefit","accidental death benefit rider","accidental death insurance","accidental death rate","accidental injury",
            "accidental injury and permanent disability cover","accidental means","accommodation","Accommodation bureaux","Accommodation ladders","Accommodation ladders with fixed steps",
            "Accommodation ladders with levelled steps","Accommodation ladders with turn tables","accommodation line","Accordions","account","account balance","account balance pension plan",
            "Account based pension","Account books","account current","account executive","account receivable - other","account rigging","Account slip pads",
            "Account slip pads and delivery or order slip pads","Account stamps","account value","accountability","accountancy","accountant","Accounterments","accounting",
            "Accounting","Accounting and Reporting by Retirement Benefit Plans","Accounting Care Organization","accounting estimatets","accounting firm","accounting for inflation",
            "accounting for life insurance companies","accounting for pension costs","accounting information","Accounting machines","Accounting on tabulating machines",
            "accounting policies","accounting policy","Accounting Principle Board","accounting standards","Accounting Standards Board","Accounting Standards Board of Japan",
            "Accounting Standards Committee","accounting system","Accounts and Statements Rules","accounts payable-trade","accounts receivable from subsidiaries and affiliates-trade",
            "accounts receivable-trade","Accreditation Program","accredited investor","accrual","accrual account","accrual accounting basis","accrual based expense and liability",
            "accrual basis","accrual bonds","accrual of benefit","accrual of pension benefit","accrual rate","accrued account","accrued benefit","accrued benefit cost method",
            "accrued benefit method","accrued business office taxes","accrued charge","accrued expenses","accrued expenses in the previous year, currently deductible",
            "accrued expenses, currently not deductible","accrued future service benefit","accrued future service benefits","accrued income","accrued interest","accrued liability",
            "accrued pension right","accrued pension rights","accrued premium","accrued right","accrued right premium","accrued salary","accrued service","accrued vacation payable",
            "accrued vacation payable in the previous year, currently deductible","accrued vacation payable, currently not deductible","acct","accumulated benefit",
            "accumulated benefit obligation","accumulated capital","accumulated contributions","accumulated depreciation","accumulated dividend","accumulated earnings",
            "accumulated interest","accumulated surplus","accumulated value","accumulated-debt problem","Accumulating machines","accumulating with-profit products",
            "accumulation","accumulation and retirement product","accumulation annuity","accumulation benefit","accumulation clause","accumulation device","accumulation fund",
            "accumulation life stage","accumulation method","accumulation of social overhead capital","accumulation period","accumulation product","accumulation side fund",
            "accumulation type policy","accumulation type product","accumulation unit","accumulation value","accumulative single premium retirement annuity",
            "Accumulator boxes","Accumulator jars","Accumulators, electric","Accumulators, electric, for vehicles","accusation","ACD","ACE","Acenaphthene","Acetaldehyde",
            "Acetanilide","Acetate","Acetate circular knit fabrics","Acetate fabrics","Acetate filament fabrics","Acetate filament yarn","Acetate of cellulose, unprocessed",
            "Acetate of fusel oil","Acetate tapes","Acetate warp knit fabrics","Acetate yarn","Acetates","Acetates for pharmaceutical purposes","Acetic acid","Acetic anhydride",
            "Aceticacid cellulose excelsior","Aceto-acetanilide","Acetoacet-o-chloroanilide","Acetoacet-o-tuluidide","Acetone","Acetones","Acetyl eugenol","Acetyl isoeugenol",
            "Acetyl Nitrocellulose","Acetyl-nitrocellulose","Acetylcholine, derivatives and preparations","Acetylene","Acetylene black","Acetylene burners",
            "Acetylene cleaning apparatus","Acetylene flares","Acetylene gas generators","Acetylene generators","Acetylene tetrachloride","ACH","ACHA","achieve high economic growth",
            "achieved profit","achieved profit method","achievement allowance","achievement appraisal","achievement in cutting down major injuries","Achillea plants",
            "Achimenes","Achimenes seeds","Achromat objective","Acid beverages, manufactured from milk or dairy products","Acid dye type pigments","Acid dyes","Acid hydrometers",
            "Acid mordant dyes","Acid or alkali proof tanks","Acid preparations","Acid preparations; limonade of citric acid, etc.","Acid proof chemical compositions","Acidimeters for batteries",
            "Acids","Acids for pharmaceutical purposes","Acids, anhydrides, non-cyclic and salt of non-cyclic organic acids","Acids, non-cyclic","Acidulated water for recharging accumulators",
            "Acidulated water for recharging batteries","ACII","Acintillation cameras","acknowledgment","ACL","ACLI","ACO","ACOEM","Aconitine","Aconitum","Acoustic acoustmeters",
            "Acoustic alarms","Acoustic conduits","Acoustic couplers","Acoustic emission equipment","Acoustic stimulators","Acoustic vibration testing machines","Acoustmeters",
            "ACP","ACP test","acquire shares","acquisition","acquisition commission","acquisition commissions","acquisition cost","acquisition value","acreage reduction policies",
            "Acridin, derivatives and preparations","Acridine derivatives and preparations; acrinol, etc.","Acridine, derivatives and preparations; acrinamine, etc.",
            "Acrilo-nitrile circular knit fabrics","Acrilo-nitrile filament fabrics","Acrilo-nitrile warp fabrics","Acrilo-nitrile weft knit fabrics","Acrolein","ACRS",
            "Acrylate-butadiene rubber","Acrylic","Acrylic denture base resins","Acrylic filament yarn","Acrylic resin adhesives","Acrylic resin clear","Acrylic resin emulsion adhesives",
            "Acrylic resin enamel","Acrylic resin paints","Acrylic resin paints, air type","Acrylic resin paints, baking type","Acrylic resin priming coat","Acrylic resin teeth",
            "Acrylic resins","Acrylic resins for crowns","Acrylic resins, unprocessed","Acrylic rubber","Acrylic yarn","Acrylonitrile","Acrylonitrile-butadien rubber adhesives",
            "Acrylonitrile-butadiene rubber","Acrylonitrile-butadiene rubber adhesives","Acrylonitrile-butadiene rubber latex adhesives","ACS","act","ACT","act of dispute",
            "act of God","Act on Stabilization of Supply","ACTA","Actinium","Actinometers","Actinomycin D and preparations","action","action in damages","Actions","Activated carbons",
            "active","active bond crowd","active employee","active investment","active life","active life reserve","active management","Active rudders","active stock","activity of daily living",
            "actual authority","actual cash value","actual contribution percentage","actual cost","actual cost of living","actual death","actual death strain","actual deferral percentage",
            "actual insurance","actual liquidation value","actual pension cost","actual return on plan assets","actual strain","actual working hours","actuarial appraisal",
            "Actuarial Approach for Financial Risks","actuarial assumption","actuarial calculation factor","actuarial consultant","actuarial cost method","actuarial deficiency",
            "actuarial funding method","actuarial gain or loss","actuarial guideline","actuarial increase","actuarial investigation","actuarial liability","actuarial mathematics",
            "actuarial methodology","Actuarial Opinion and Memorandum","actuarial present value","actuarial principle","actuarial profession","actuarial rating","actuarial reduction",
            "actuarial report","Actuarial Research Clearing House","actuarial revaluation","actuarial science","Actuarial services","Actuarial Society of America","Actuarial Standard of Practice",
            "Actuarial Standards Board","Actuarial Studies in Non-Life Insurance","actuarial valuation","Actuaries Mortality Table","Actuaries' Investment Index","actuary",
            "acupuncture","Acupuncture and moxibustion apparatus","Acupuncture and moxibustion equipment","Acupuncture apparatus suitable for home use","Acupuncture needles",
            "Acupuncture point detectors","acute cardiac insufficiency","acute care","acute disease","acute health care","ad hoc adjustment","ad hoc adjustment of salary base or flant benefit accruals",
            "ad hoc increase","Ad Hoc Liaison Committee","Ad Hoc Liasion Committee","ad valorem tax","AD&D","Ad-balloons","ADA","Adalet ve Kalkinma Partisi","adaptability","adaptation training",
            "Adaptive controlled robots","adaptive expectations","Adaptors","ADB","add-on","add-on option","add-on tax","added value","Added value base","added years","Adding machines",
            "addition","additional benefit","additional commission","additional condition","additional coverage","additional minimum liability","Additional Pension","additional premium",
            "additional risk","additional risks","additional voluntary contribution","Additives to fodder for medical purposes","Additives to fodder, not for medical purposes",
            "Additives, chemical, to drilling muds","Additives, chemical, to fungicides","Additives, chemical, to insecticides","Additives, chemical, to motor fuel","Additives, non-chemical, to Motor fuel",
            "Additives, non-chemical, to motor-fuel","Address books and visiting cardfolders","Address plates for addressing machines","Address stamps","Addressing machines",
            "ADEA","Adenine and preparations","Adenium roem","Adenosine and preparations","ADF","Adhesion pumps","Adhesive","Adhesive bands for medical purposes","Adhesive bands for pulleys",
            "Adhesive bands for stationery or household purposes","Adhesive bands other than stationery and not for medical or household purposes","Adhesive Bands, for medical purposes",
            "Adhesive fabric for application by heat","Adhesive plaster","Adhesive plasters","Adhesive preparations for surgical bandages","Adhesive rubber patches for repairing Inner tubes",
            "Adhesive rubber Patches for repairing inner tubes","Adhesive tape dispensers","Adhesive tapes for medical purposes","Adhesive tapes for stationery or household purposes",
            "Adhesive tapes other than stationery and not for medical or household purposes","Adhesive Tapes, for medical purposes",
            "Adhesive Tapes, other than stationery and not for medical or household purposes","Adhesives","Adhesives for affixing false Eyelashes","Adhesives for affixing false hair",
            "Adhesives for billposting","Adhesives for cosmetic purposes","Adhesives for dentures","Adhesives for industrial purposes","Adhesives for paperhanging",
            "Adhesives for stationery or household purposes","Adhesives for wall tiles","Adhesives for Wallpaper","Adhesives, other than for stationery or household purposes",
            "Adiantum","Adipate plasticizers","Adipic acid","adjudicator","adjust economy","adjust something to demand","adjust supply and demand","adjust the discount rate",
            "Adjustable adapters","Adjustable lathe dogs","adjustable life insurance","adjustable premium","Adjustable rack clamps","Adjustable rack type blocks","adjustable rate mortgage",
            "adjustable rate preferred","Adjustable reamers","Adjustable reamers with pilot","Adjustable round split dies","Adjustable table single action single crank presses",
            "Adjustable wrenches","adjusted death rate","Adjusted Earnings","adjusted gross income","adjusted pay-as-you-go system","adjusted pension plan","adjusted premium",
            "adjusted premium method","adjusted surplus","adjustment bond","adjustment for risk and uncertainty","Adjuvants for medical purposes","ADL","administered price",
            "administration","administration charge","administration cost","administration expenses","Administration on Aging","administrative agency","administrative charge",
            "administrative cost","administrative expenses","administrative fee","administrative guidance","administrative law","administrative license procedure","Administrative processing of purchase orders",
            "administrative remedy","administrative rules and regulations","administrative services only","administrative services only contract","administrator","admissible assets",
            "admission","Admission tickets","admitted assets","admitted company","ADN","adoption","Adoption agency services","ADP","ADP test","ADR","Adrenal cortex preparations",
            "Adrenal hormone preparations","Adrenocortical hormone preparations","Adrenocorticotropic hormone preparations","ADS"]
        
        ReturnWordArray += wordStore
        
        
        //http://ejje.weblio.jp/category/business/a/9
        //http://ejje.weblio.jp/category/business/a/17
        wordStore = ["ADTA","adult","Adult beef bulls","Adult beef cattle","Adult beef cattle steers","Adult beef steers","Adult boars for breeding","Adult boars for breeding, non-registered",
            "Adult boars for breeding, registered","Adult dairy steers","adult day care","adult disease","Adult draft geldings","Adult draft horeses","Adult draft mares","Adult goats",
            "Adult goats, female","Adult goats, female, non-registered","Adult goats, female, registered","Adult goats, male","Adult goats, male, non-registered","Adult goats, male, registered",
            "Adult hogs for breeding","Adult sheep","Adult sows for breeding","Adult sows for breeding, registered","Adult sows for breeding,non-registered","Adult ventilators",
            "advance","advance corporation tax","advance funded pension","advance funding","advance funding method","advance notice","advance payment","advance premium","advance receipt",
            "advance refunding","advance to agent","advance-decline ratio","advance-in-age plan","advanced age","Advanced Financial Planning Certificate","advanced fixed fee",
            "advanced industrial structure","advanced life underwriter","advanced life underwriting","advanced technology","advancement","advancement in age","advances paid",
            "advances payments","advances received","adverce deviation","adverse deviations","adverse effect","adverse opinion","adverse selection","adverse-experience risk",
            "adversely affected","advertisement","Advertisement boards of paper or cardboard","Advertisement columns of metal","Advertisement columns, not of metal","advertisement for recruitment",
            "Advertisements of Accident and Sickness Insurance Model Regulation","Advertisements of Life Insurance and Annuities Model Regulation","Advertising","Advertising agencies",
            "Advertising by mail order","Advertising displays","Advertising steel towers","advice based product","adviser","adviser charging","Advisory Commission on Intergovernmental Relations",
            "Advisory Council on Social Security","advisory insurance organization","Advisory services for business Management","advocate","advocate-general","Adzes","AE","AE agents",
            "Aechmea","AEI","Aerated beverages making machines","Aerated water","Aerated water making apparatus","Aerating pumps for aquaria","Aeration machines","Aeration pumps",
            "Aerators","Aerial and surface spreading of fertilizers and other agricultural chemicals","Aerial cameras","Aerial conveyors","Aerial lift truck bodies",
            "Aerial navigation sextants","Aerial projectors","Aerial ropeways","Aerials","Aerocondensers","Aerofall mills","Aerometers","Aeronautical apparatus, machines and appliances",
            "Aeronautical electronics equipment","Aeronautical electronics equipment and radio equipment","Aeronautical engines","Aeronautical radio equipment","Aeroplane engines",
            "Aeroplanes","Aeroslides","Aerosol dispensers for medical purposes","Aerosol dispensers, not for medical purposes","Aeschyhanthus","Aetna/Generali International Benefits Network",
            "AF cameras","AF cameras with zoom lens","AF single lens reflex cameras","AFAR","AFBD","AFC equipment","AfDB","AFDC","affect the economy","affect the exchange rate",
            "affidavit","affiliate","affiliated companies","affiliated company","affiliation","affinity","affinity group","affinity market","affinity marketer","affinity marketing",
            "affirmative action","affirmative consent","afflicted people","affordable health care","affordable health care for all","Afganistan National Development Strategy",
            "AFIR","AFL-CIO","AFP","AFPC","Africa Partnership Forum","Africa-Asia Business Forum","African Development Bank","African Mission in Burundi","African National Congress",
            "African Union","African Union Mission in Somalia","African Union/United Nations Hybrid operation in Darfur","African violet","AFT","AFTA","After treating machinery",
            "after-effect","after-hours trading","After-shave lotions","aftertax income","aftertax profit","AG","Agapanthus","Agar-agar","Agar-agars","Agate","Agates","AGC equipment",
            "age","age at entry","age at exit","age at which pensions are awarded","age based premium","age based premiums","age composition","age discrimination",
            "Age Discrimination in Employment Act Amendments of 1978","age group","age joining limit","age last birthday","age limit","age limit system","age limit system for managerial personnel",
            "age mix","age nearest birthday","age next birthday","age of eligibility","age of insured","age of policy","age pension","age pension scheme","age population",
            "age rate-up","age rate-ups","age rating","age related NI rebates","age related payment","age related rebates","age setback","age specific mortality rate",
            "age structure","age-adjusted death rate","age-earning profile","Age-kamaboko","age-linked wages","age-rated system","age-wage profile","age-wave","age-weighted profit sharing plan",
            "aged","Aged Pension","aged poor","aged population","aged society","aged society with a low birth rate","ageing","ageism","agency","agency commission","agency company",
            "agency contract","agency cost","agency department","agency distribution system","agency expense","agency field","Agency for Health Care Policy and Research",
            "agency force","agency law","agency management","Agency Management Training Course","agency manager","agency operation","agency operations","agency residency requirement",
            "agency residency requirements","agency securities","agency staff","agency supervisor","agency system","agency theory","agency-building company","agent",
            "agent based channel","agent commission","agent commission structure","agent commission system","agent compensation system","agent contract","agent distribution system",
            "agent license","agent licensing","agent produced life policy","Agent Production and Survival","agent recruiting","agent retention","agent salary plan","agent union",
            "agent-owned company","agent-owned insurance company","agent-owned reinsurance company","Agents activating cellular function","Agents activating cellular function, n.e.c.",
            "Agents affecting cellular function","Agents affecting central nervous system","Agents affecting circulatory organs, respiratory organs and urinary organs",
            "Agents affecting digestive organs","Agents affecting genital organs","Agents affecting individual organs","Agents affecting metabolism","Agents affecting metabolism, n.e.c.",
            "Agents affecting nervous system","Agents affecting nervous system and sensory organs","Agents affecting peripheral nervous system","Agents affecting respiratory organs",
            "Agents affecting sensory organs","Agents affecting urinary organs","Agents against parasites","Agents against pathogenic micro-organisms and parasites",
            "Agents against pathogenic organisms and parasites","Agents and Brokers Licensing Model Act of 1973","Agents and related commodities used for animals",
            "Agents for artificial dialysis","Agents for artificial inseminations","Agents for artificial kidney dialysis","Agents for bacteriological tests","Agents for breeding",
            "Agents for dental and oral use","Agents for dispensing use","Agents for epidermis","Agents for epidermis, n.e.c.","Agents for external use","Agents for habitual intoxication",
            "Agents for hoots","Agents for hyperlipidemias","Agents for liver disease","Agents for liver disease and antidotes","Agents for mastitis","Agents for not mainly purpose of therapeutic",
            "Agents for not mainly purpose of therapeutic, n.e.c.","Agents for ophthalmic use","Agents for otic and nasal use","Agents for pediatric use","Agents for peptic ulcer",
            "Agents for peritoneal dialysis","Agents for protective skin","Agents for public health","Agents for public health, n.e.c.","Agents for stimulation therapy",
            "Agents for treatment of gout","Agents for uro-genital and anal organs","Agents relating to blood and body fluides","Agents relating to blood and body fluides, n.e.c.",
            "Agents used for common cold","agents' allowance","agents' authority","agents' balance","agents' expense","agents' note","agents' qualification laws","agents' report",
            "Ageratum seeds","Ageratums","ages based on job evaluation","Agglomerated Bagasses of cane","Agglutinants for concrete","Agglutinants for paints","aggravated risk",
            "Aggregate","Aggregate cooling equipment","aggregate cost method","aggregate cost ratio","aggregate demand","aggregate demand schedule","aggregate indemnity",
            "aggregate indemnity plan","aggregate liability","aggregate method","aggregate mortality table","aggregate personal savings","Aggregate spreaders",
            "aggregate standard class","aggregate supply","aggregate table","Aggregated wood machines","Aggregating machines","aggressive growth fund","aggressive stock",
            "AGI","AGIC","aging","aging index","aging measurement","aging of population","aging population and lower birthrate","aging process","aging society","agism",
            "Agitation type cleaning machines","Agitation type washing machines","Agitator type flotation machines","Agitators","AGM","agreement","Agreement on Internal Trade",
            "agreement on overtime","Agreement on Trade-Related Aspects of Intellectual Property Rights","AGRI Benefits Network","Agricultural and incustrial micro-organisms",
            "Agricultural Bank Insurance Joint Stock Corporation","Agricultural chemicals","Agricultural driers","Agricultural elevators","Agricultural gloves","Agricultural implements other than hand-operated",
            "Agricultural implements, hand-operated","agricultural land reform","Agricultural machines","Agricultural material products, edible, n.e.c.","agricultural price",
            "AGRICULTURAL PRODUCTS","Agricultural tractors","Agricultural trailers","Agricultural water","agriculture","Agriculture and Rural Areas Basic Act","Agriculture, forestry and fishery",
            "Agriculture, forestry, stockbreeding, hunting and fishing","AHA","AHCA","AHCPR","AHIA","AHIP","AHLC","AHS","AI","AIA","Aiamond","AIB","AIBD","Aibu-wakame","AIC",
            "AICPA","AICPCU","Aid Association for Lutherans","Aid for Trade","aid fund for starting a business","aid of re-entry into employment","Aid to Families with Dependent Children",
            "Aid to the Permanently and Totally Disabled","AIDA","aide","AIDS","aids and adaptions","AIDS precaution life style questionnaire form","AIDS testing law",
            "AIDS-Related Complex","AIDS/HIV test","AIDS/HIV testing","AIFA","AIG","AII","AIIC","Aikido equipment","ailment","AILO","AIM","AIME","AIPLU","Air analysis apparatus",
            "Air analyzers","Air and space-craft wires","Air bags","Air balloons","Air blast machines","Air brake assy","Air brake equipment","Air brake hoses for railway rolling stock",
            "Air brushes for applying colour","Air classifiers","Air compressors","Air condensers","Air conditioners and related equipment","Air conditioners for air－transportation",
            "Air conditioners for transportation machines","Air conditioners for vehicles","Air conditioning apparatus","Air conditioning apparatus installation and repair",
            "Air conditioning facilities","Air conditioning facilities for transportation","Air conditioning facility components","Air conditioning hoses assemblies for automobiles",
            "Air conditioning installations","Air conditioning units","Air cooled diesel engines","Air cooled four-cycle gasoline engines","Air cooled gasoline engines",
            "Air cooled gasoline outboard engines","Air cooled kerosene engines","Air cooled transmitting tubes","Air cooled two-cycle gasoline engines","Air cooling apparatus",
            "Air cushion conveyors","Air cushion crafts","Air cushion devices for moving loads","Air cushion vehicles","Air cushions for medical purposes","Air cushions, not for medical purposes",
            "Air deodorising","Air deodorising apparatus","Air dried flooring boards","Air driers","Air Dryers","Air dynamometers","Air film conveyors","Air filtering installations",
            "Air filters","Air freshening","Air freshening preparations","Air freshers","Air gun pellets","Air guns","Air hammers","Air handling units","Air lift pumps","Air lockers",
            "Air mattresses, for medical purposes","Air mattresses, not for medical purposes","Air micrometers","Air mills","Air operated chucks","Air operated control valves",
            "Air permeability testing machines","Air pillows for medical purposes","Air pillows, not for medical purposes","Air pistols","air pocket stock","Air pollution control equipment",
            "Air pollution monitoring equipment","Air pollution monitoring instruments","Air ports","Air preheaters","Air pumps","Air purification","Air purifiers","Air purifying apparatus and machines",
            "Air purifying preparations","Air reheaters","Air sifters","Air sterilisers","Air suction machines","Air tanks","Air transport","Air treatment equipment","Air turbine handpieces",
            "Air type","Air valves for steam heating installations","Air vehicles","Air-conditioning installations and apparatus","Air-conditioning installations for vehicles",
            "Air-cured","Air-plast sprayers","Air－cleaners and air-filters","Air－handling units","Airblast circuit breakers","Airborne","Airborne radar equipment",
            "Airborne radio communication equipment","Aircraft","Aircraft accessories","Aircraft ground facilities","aircraft passenger accident insurance","Aircraft tires",
            "Aircraft towers and such amusement equipment","Aircraft tubes","AIRCRAFT,ROCKETS AND SATELLITES","Airctaft","Airdrome type","AIREA","Airframe assemblies","Airframe parts",
            "Airframe parts and assemblies","AIRMIC","Airplane maintenance and repair","Airplanes","Airport and airway lamps","Airport service truck bodies","Airport signal lights",
            "Airships","Airtight sealing equipment","AISAM","AIT","AIU","AJCEP","Aji-bushi","Ajiro stitching machines","Ajowan oil","AKP","ALA","Alabalster glass balls for imitation pearls",
            "Alabaster","Alabaster glass","Alabaster glass rods for imitation pearls","Alarm bells, electric","Alarm clocks","Alarm dosemeters","Alarm fuses and alarm fuse units",
            "Alarm signal automatic receivers","Alarm systems and signal systems","Alarm units","Alarms","Alaska pollack","Alaska pollack oils","ALBA","Albacore","albumen","Albumen",
            "Albumen for food","Albuminized paper","Albuminous foodstuffs for medical purposes","Albuminous milk","Albuminous preparations for medical purposes","albuminuria",
            "Albums","Albums, photograph corners and photograph mounts","Alcohol","alcohol abuse","Alcohol and preparations","Alcohol burners","Alcohol for pharmaceutical purposes",
            "Alcohol, aldehyde and preparations","Alcohol-polyethylene glycol ether","alcoholic","Alcoholic beverage bottles","Alcoholic beverage cans","Alcoholic beverage containers",
            "Alcoholic beverage making machines","Alcoholic beverages","Alcoholic beverages containing Fruit","Alcoholic Beverages containing fruit","Alcoholic beverages fermented from cereals",
            "Alcoholic beverages, except beer","Alcoholic beverages, n.e.c.","Alcoholic essences","Alcoholic extracts","alcoholism","Alcoholmeters","Alcohols, non-cyclic",
            "Aldehyde C10","Aldehyde C11","Aldehyde C12","Aldehyde C13","Aldehyde C14","Aldehyde C16","Aldehyde C18","Aldehyde C6","Aldehyde C8","Aldehyde C9","Aldehydes","Aldehydes for pharmaceutical purposes",
            "Aldehydes, non-cyclic","aleatoric contract","aleatory contract","Alfalfa seeds","Algae for human or animal consumption","Algarovilla","Algarovilla for animal consumption",
            "Algicides","Alginates for food","Alginates other than for alimentary purposes","Alginic acid","Alginic acid, derivatives and preparations","ALHC","ALI","ALIC","Alidades",
            "Alien checking equipment","alien insurer","alienation","Alighting gears","Alignment telescopes","ALIMDA","Alissums","Alizarine dyes","Alkali salts of sulphonated riconoleic acids",
            "Alkalies","Alkaline batteries","Alkaline iodides for industrial purposes","Alkaline iodides for pharmaceutical purposes","Alkaline manganese dioxide batteries",
            "Alkaline metals","Alkaline preparations","Alkaline preparations; potassium hydroxide, etc.","Alkaline preparations; sodium sesquicarbontae, etc.","Alkaline-earth metals",
            "Alkaloidal narcotics","Alkaloids","Alkaloids and preparations","Alkaloids and preparations; emetine hydrochloride, etc.","Alkaloids and preparations; strychnine, etc.",
            "Alkaloids and preparations; tubocurarin, etc.","Alkaloids for medical purposes","Alkamine aminobenzoates and preparations","Alkid resins","Alkyd resin paints",
            "Alkyl acethy indan musks","Alkyl acethy tetrahydronaphthaline musks","Alkyl amide pyridinium halides","Alkyl amine and alkylol amine fatty acid salts",
            "Alkyl amine polyethylene glycol addition products","Alkyl aminobenzoates and preparations","Alkyl ammonium halides","Alkyl aryl polyethylene glycol ether",
            "Alkyl benzen sulphonate","Alkyl naphthalene sulphonate","Alkyl oxymethyl pyridinium halides","Alkyl oxytrirthyl ammonium halides","Alkyl phosphate","Alkyl pyridinium halides",
            "Alkyl pyridinium salts","Alkylating agents","Alkylol amide","Alkylol amine polyethylene glycol addition products","All casing boring machines","All Net",
            "All Net program","All purpose finishing machines","all savers certificate","All spices","All-leather","all-lines","all-lines insurance","all-lines insurer","All-terrain cranes",
            "allegation","allergist","allergy","allfinance","Allfinanz","Allfinanzier","Alliance for Aging Research","Alliance for Managed Competition","Alliance for the Separation of Banking and Insurance",
            "Alliance of American Insurers","Allicyclic compounds","Alligater and crocodile leather","Alligator and crocodile leather, n.e.c","alligator spread","Alligatter shears",
            "Allium","Allium bulbs","allocated benefit","allocated contract","allocated funding","allocated funding instrument","Allocated pension","allocation","allograft",
            "Allopurinol and preparations","allotment","allowance","allowance for annual leave","allowance for doubtful accounts","allowance for investment loss","allowance for night or day watch",
            "allowance for specific duty","allowance for supervisory post","allowed assets","Alloy iron castings","Alloy steel","Alloy steel for structure","Alloy steel scrap",
            "Alloy steel scrap other than stainless steel scrap","Alloy tool steel","Alloys for dental amalgam","Alloys of common metal","Alloys of precious metal",
            "Alloys of precious metals for dental purposes","Allspice","Allyl alcohol","Allyl caproate","Allyl chloride","Allyl cyclohexylpropionat","Allyl resin","ALM",
            "Almanacs","Alminium food storage utensils","Almond confectionery","Almond milk for cosmetic purposes","Almond oil","Almond paste","Almond soap","Almonds","Almonds, ground",
            "ALMS","almshouse","Alocasias","Aloe","ALOS","Alpaca hair","Alpaca lining","Alpenstocks","Alpha cereal","Alpha rice","Alsike clover seeds","Alstoromeria plants","Alstroemeria",
            "Alt-azimuth mounting","Altars","Altars, its ornament and betrothal presents goods","alteration of policy","alternate care","alternate policy","Alternating and direct current",
            "Alternating current","Alternating current discharge processing equipment","Alternating current stabilized power source equipment","Alternating low frequency electric therapy equipment",
            "Alternativa Bolivariana para las Américas","alternative delivery system","alternative delivery system benefit","Alternative Dispute Resolution","alternative distribution system",
            "alternative format","alternative GIC","alternative healthcare delivery system","alternative healthcare system","alternative hypothesis","alternative insurance",
            "alternative investment","Alternative Risk Transfer","Alternative Safe Harbor Test","Alternators","Alterranthera","Altimeters","Alto-saxhorns","altruism","ALU","Alum",
            "Alum stones","Alumina","Alumina cement","Alumina lumps","Alumina sized grains and powders","Alumina-carbon bricks","Aluminium","Aluminium acetate","Aluminium acetate for pharmaceutical purposes",
            "Aluminium acetate, basic","Aluminium alloy ingots","Aluminium alloy ingots die-castings","Aluminium alloy ingots for castings","Aluminium alloy ingots for wrought products",
            "Aluminium alloy wires","Aluminium alum","Aluminium and aluminium alloy rolling mill rolls","Aluminium and aluminium alloys castings","Aluminium and aluminium alloys castings diecastings and sintered products",
            "Aluminium and aluminium alloys die-castings","Aluminium and aluminium alloys sintered products","Aluminium and aluminium alloys, n.e.c.","Aluminium and aluminium-base alloy scrap and waste",
            "Aluminium bronze castings","Aluminium bronze products","Aluminium bronze scrap","Aluminium cans for drink","Aluminium chloride","Aluminium chlorides","Aluminium clad steel wires",
            "Aluminium compounds","Aluminium conductor appliance wires","Aluminium conductor power wires and cables","Aluminium conductor steel reinforced","Aluminium conductor telecommunication wires and cables","Aluminium conductor winding wires","Aluminium conductor wires and cables for transpoter","Aluminium cooking utensils","Aluminium copper","Aluminium doors",
            "Aluminium fluoride","Aluminium fluoride type","Aluminium foil","Aluminium hydrate","Aluminium hydroxide","Aluminium iodide","Aluminium metal for electric purpose",
            "Aluminium nitrate","Aluminium ores","Aluminium oxide","Aluminium paint","Aluminium paints","Aluminium Powder for painters, artists and decorators","Aluminium powder for painting",
            "Aluminium preparation utensils","Aluminium sashes","Aluminium scrap","Aluminium silicate","Aluminium soaps","Aluminium stranded conductor, aluminium clad steel reinforced",
            "Aluminium sulphate type purifying compounds","Aluminium sulphates","Aluminium table utensils","Aluminium tableware","Aluminium wires","Aluminium-base alloy scrap",
            "Aluminium-base master alloys","Aluminium-coated steel strips and hoops","Aluminium-copper products","Aluminium-silicon products","Alumino sodium silicate",
            "Aluminous shale","Aluminum compounds and preparations; aluminum hydroxide, aluminum silicate, etc.","Aluminum-coated steel strips","Aluminum-costed steel sheets",
            "Alums","Alunite","Alyssum seeds","Alzheimer's dementia","Alzheimer's disease","AMA","Amaaji-kombu","Amacrinum bulbs","Amado","Amado with fire proofing","Amado with ventilation",
            "Amantadine and preparations","Amaranthus seeds","Amaryllis","Amaryllis bulbs","Amazon lily","AMBAC","Amber","Ambergris, refined","Amberjack","Ambient heavy metal analyzers",
            "Ambrettolide","Ambroid bars","Ambroid plates","Ambry hemp","ambulance","Ambulance bodies","Ambulance stretchers","Ambulance transport","Ambulances","ambulatory health care",
            "ambulatory health care delivery","ambulatory patient","ambulatory surgical center","AMCRA","AME","amendment","amendment assessment","America's Health Insurance Plans",
            "American Academy of Actuaries","American Academy of Insurance Medicine","American Annuitants Table","American Annuitants Table of Mortality","American Arbitration Association",
            "American Association for Long-term care Insurance","American Association of Bank Holding Companies","American Association of Health Plans","American Association of Homes for the Aging",
            "American Association of Individual Investors","American Association of Managing General Agents","American Association of Preferred Provider Organizations",
            "American Association of Private Pension and Welfare Plans, Inc.","American Association of Retired Persons","American Bankers Association","American Bar Association",
            "American Benefits Council","American College","American College of Hospital Administrators","American College of Occupational and Environmental Medicine",
            "American College of Physicians","American College of Surgeon","American Council of Life Insurers","American Dental Association","American Depositary Receipt",
            "American Experience Table","American Experience Table of Mortality","American Express Company","American Federation for Aging Research","American Federation of Labor & Congress of Industrial Organizations",
            "American football bladders","American football equipment","American grape hyacinth","American Health Benefit Exchange","American Health Care Association",
            "American Health Security Act","American Health Security Act of 1993","American Healthcare Systems","American Hospital Association",
            "American Institute for Chartered Property Casualty and Underwriters","American Institute for Property and Liability Underwriters, Inc.","American Institute of Actuaries",
            "American Institute of Certified Public Accountants","American Institute of Real Estate Appraiser","American Insurance Association","American International Group, Inc.",
            "American International Underwriters Corporation","American Law Institute","American Life Convention","American Life Insurance Association","American Medical Association",
            "American Medical Care and Review Association","American Medical International, Inc.","American Medical Peer Review Association","American Men Table","American Men Ultimate Mortality Table",
            "American Municipal Bond Assurance Corporation","American Nurses Association","American process","American Recovery and Reinvestment Act","American Risk & Insurance Association, Inc.",
            "American Savings Education Council","American Service Bureau, Inc.","American Society of CLU and ChFC","American Society of Pension Actuaries","American Stock Exchange",
            "American summer pearmain","American wormseed","Americans With Disabilities Act of 1990","Americium","Amex","AMEX Index","AMI","Ami-kusa","Ami-shiokara",
            "AMIB","Amicable Society","Aminal wool rock","Aminitrozole and preparations","Amino acid and preparations","Amino acids for medical purposes","Amino acids for veterinary purposes",
            "Amino alkyd resin paints","Amino alkyd resin priming coat","Amino resins","Amino salicylic acid","Aminoacetic acid, derivatives and preparations",
            "Aminoglycoside derivatives and antibiotic preparations","Aminonaphtholsulphonic acids, sodium salts","Aminoquinolines and preparations"]
        
        ReturnWordArray += wordStore
        
        //http://ejje.weblio.jp/category/business/a/20
        wordStore = ["Amisidines","AMISOM","Amly caproate","Ammeters","Ammobium seeds","Ammonia","Ammonia alum","ammonia for industrial purposes","Ammonia for industrial purposes",
             "Ammonia preparations","Ammonia water","Ammonia, gas","Ammoniacal salts","Ammonias and ammonia water","Ammonium acetate","Ammonium aldehyde","Ammonium alum",
             "Ammonium bicarbonate","Ammonium bifluoride","Ammonium borate","Ammonium bromide","Ammonium carbonate","Ammonium chlorate","Ammonium chloride","Ammonium chromate",
             "Ammonium compounds","Ammonium compounds, n.e.c.","Ammonium dichromate","Ammonium fluoride","Ammonium hypophosphate","Ammonium iodidee","Ammonium metavanadate",
             "Ammonium molybdate","Ammonium nitrate","Ammonium nitrate explosives","Ammonium nitrate-fuel oil mixture","Ammonium paratungstate","Ammonium perchlorate",
             "Ammonium persulphate","Ammonium phosphate, dibasic","Ammonium phosphate, monobasic","Ammonium phosphates","Ammonium salts","Ammonium salts and preparations; foeniculated ammonia spirit, ammoniumchloride, etc.","Ammonium sulphamate","Ammonium sulphate","Ammonium sulphide","Ammonium sulphite","Ammonium sulphocyanide","Ammonium thiosulphate",
              "Ammunition","Ammunition for Firearms","Ammunition hoisting equipment","Ammunition,sub－caliber","amnesia","Amorphousgraphite","amortisation","amortization",
             "amortization fund","amortization method","amortization of development expenses","amortization of goodwill","amortize","amortized cost","amortized value",
             "amount applied for","amount at risk","amount due from agent","amount insured","amount of assurance","amount of currency","amount of insurance","amount of reinsurance",
             "amount of risk","amount option","AMP","Amphetamine, derivatives and preparations","Amphibious airplanes","Amphibious excavators","Amphibious tractors",
             "Amphibole asbestos concentrates","Amphibole asbestos crude ore","Amphoteric soap and preparations","Amphoteric surface-active agents","Amphoteric synthetic detergents",
             "Amphotericin B and preparations","Amplifiers","Amplifiers and tuners","Amplifiers,detectors and modulation meters","Amplifying tubes","Amplifying valves",
             "Ampoules","Amputating instruments","Ams","AMTC","AMU","Amulets","Amunzen","Amur adonis","Amusement apparatus adapted for use with an external display screen or monitor",
             "Amusement machines, automatic and coin-operated","Amusement parks","Amusements","AMW","Amyl acetate","Amyl acetates","Amyl alcohol","Amyl alcohols","Amyl benzoaten",
             "Amyl butyrate","Amyl caprylate","Amyl cinnamate","Amyl formate","Amyl phenylacetate","Amyl propionate","Amyl salicylate","Amyl succinate","Amyl valerate","amyloid",
             "an assigned employee","an assignee company","an assignor company","an employer who is obliged to withholding income tax","ANA","Anabolic steroid hormone and preparations",
             "Anabolic steroids and preparations","anaemia","Anaesthetic apparatus","Anaesthetic masks","Anaesthetics","Analgesics","Analgesics and sedatives for dental use, including antiseptics of rootcannal and carrious cavity","Analgesics, anti-itchings, astrigents and anti-inflammatory agents","Analog computers","Analog controllers","Analog oscilloscores",
            "Analog voltmeters and ammmeters","Analog-digital convertors","Analogue electronic switching equipment","Analogue transmission equipment","Analysis for oil-field exploitation",
            "analysis of profit","analyst","Analytical instruments","Analytical X-ray tubes","Analytical,n.e.c.","Analyzers for heavy metals in water","anamnesis",
            "Anamorphic lenses","Anamorphic lenses for motion picture cameras","Anatase type","Anbrette seed oil","ANC","ancestor","Anchor chains","Anchor lights","Anchor plates",
            "Anchors","Anchovy","Ancient Kokeshi dolls","Anciliary facilities for radio communication","ancillary benefit","ancillary risk","and interest","Andalusite",
            "Andean Community of Nations","Andes","Andesite","Andesite and basalt","Androgen preparations","ANDS","anemia","Anemometers","Anemone","Anemone bulbs","Anemone hupehensis",
            "Anemone plants","Anemone seeds","Aneroid manometers","Aneroid type indicating manometers","anesthesia","Anesthesia apparatus","Anesthesia apparatus,rebreathing bags and gas absorbers",
            "Anesthesia mixing apparatus","anesthetist","Anethole","aneurism","aneurysm","angel","Angel type","Angelica oil","angina","angina pectoris","Angio- polygraphs",
            "Angiographic X-ray equipment","angiography","angioplasty surgery","Angiotensin converting enzyme inhibitors","Angle block gauges","Angle cutters","Angle dozers",
            "Angle finders for motion picture photography","Angle gauges","Angle irons","Angle irons, not of metal","Angle measuring machines and instruments",
            "Angle reading instruments","Angle shears","Angle surveying instruments","Angle surveying instruments,n.e.c.","Angle valves","Angle,position and displacement meters",
            "Angling","Angling accessories","Angling fishing boats","Angling lines","Angling machines","Angora goat hair","Angora rabbit hair","Angora rabbits",
            "Angostura bark for medical purposes","Angraecum bory","Angular bevel gears","Angular contact ball bearings","Angular contact thrust ball bearings","Angular milling cutters",
            "Angular spindle units","Angular spiral bevel gears","Angular straight bevel gears","Angular tables","Angular wheel head cylindrical grinding machines",
            "Anhydrides","Anhydrides, non-cyclic","Anhydrous ammonia","Anigozanthus","Aniline","Aniline derivatives and preparations; mefenamic acid, flufenamic acid,etc.",
            "Aniline dyes","Animal albumen","Animal breeding","Animal Bristles","Animal carbon","Animal carbon preparations","Animal charcoal","Animal Claws",
            "Animal drawn harrows","Animal drawn harrows, Japanese type","Animal drawn ploughs","Animal drawn ploughs, Japanese type","Animal drawn vehicles",
            "Animal examination apparatus for research","Animal fat","Animal fattening preparations","Animal fibres","Animal fibres, n.e.c.","Animal filament yarn",
            "ANIMAL FOODS","Animal foodstuffs","Animal glues","Animal grooming","Animal hair","Animal hair and silk worm filament","Animal hair tops","Animal hairs, feathers and downs",
            "Animal hooves","Animal horns","Animal marrow for food","Animal materials used in manufacturing drugs","Animal oils and fats, except fish and marine mammal oils and fats",
            "Animal protein supplements","Animal skins","Animal training","Animal washes","Animal wax","Animated cartoons","Animation camera stands","Anion exchange resin",
            "Anionic surface-sctive agents","Anionic synthetic detergents","Anise","Aniseed","Aniseed oils","Anisette","Anisic alcohol","Anisicaldehyde","Anisidined",
            "Anisyl acetate","Anisyl formate","Anman","Annatto","Annealing equipment","Annealing furnaces","anniversary","anniversary date","Annotto","Announcement cards",
            "Annual and biennial potted flowers","annual compensation package","annual declaration","annual dividend policy","annual earnings","annual expenditure","annual information return",
            "annual interest rate","annual meeting","annual paid holidays","annual percentage rate","annual premium","annual renewable term","annual renewable term insurance",
            "Annual renewal of labor insurance","annual report","Annual reports","Annual Return","annual revenue","annual salary","annual salary system","Annual Security Outlook",
            "annual statement","annual summary","annual wage increase","annualized near business premium","annualized near premium","annualized new business premium",
            "annualized premium","annually deductible","annually renewable term","annually renewable term insurance","annuitant","annuitants'mortality table","annuitization",
            "annuitization rates","annuity","Annuity 2000 Mortality Table","annuity agreement","annuity benefit","annuity benefits","annuity bond","annuity certain","annuity certain and continuous",
            "annuity company","annuity consideration","annuity contract","annuity cost","annuity distribution","annuity due","annuity for life","annuity fund deposit",
            "annuity immediate","annuity in perpetuity","annuity income","annuity income payments","annuity insurance","annuity mortality table","annuity option","annuity payment age",
            "annuity payments","annuity payout","annuity payout option","annuity period","annuity policyholder","annuity premium","annuity product","annuity purchase formula",
            "annuity rates","annuity refund","annuity reinsurance","annuity reserve","annuity risk","annuity settlement option","Annuity Table for 1949","annuity territory",
            "annuity unit","annuity value","Annular screw plates","Annunciator signal systems","Anode batteries","Anode for aluminium production","Anodes","anorexia","Anoscopes",
            "another-insured rider","ANP","Answering machines","Antacids","Antarctic krill meal","antedating policy","Antelope leather","Antenna coupling equipment","Antenna driving systems",
            "Antenna parameter measuring instruments","Antenna sockets","Antennas","Antennas for motor vehcile equipment","antennas,n.e.c.","Anterior cameras",
            "Anterior petuitary gonadotrophic hormone and preparations","Anterior pituitary hormone preparations","Anthelmintics","Anthelmintics for digestive organs",
            "Anthracene and phenanthrene derivatives","Anthracene, crude","Anthracene, refined","Anthracenes","Anthracite","Anthracite and natural coke","Anthranilic acid",
            "Anthraquinone","Anthraquinone derivatives, crude drugs and preparations","Anthropology","Anthurium","Anti plasminic preparations","Anti-aircraft binocular telescopes",
            "Anti-aldosterone preparations; triamterene, etc.","anti-alienation","anti-biotics","anti-body","Anti-boil preparations for engine coolants","anti-cancer drug",
            "Anti-corrosive bands","Anti-corrosive preparations","Anti-Counterfeiting Trade Agreement","anti-cutback rule","Anti-dazzle devices for automobiles",
            "Anti-dazzle devices for vehicles","Anti-dazzle films for windows","Anti-dazzle shades","Anti-dermoinfectives","anti-discrimination","Anti-fouling paints",
            "Anti-friction bearings for machines","Anti-friction metal","Anti-friction pads for machines","Anti-frothing solutions for accumulators","Anti-frothing solutions for batteries",
            "Anti-glare devices for vehicles","Anti-glare glasses","Anti-glare visors","Anti-histaminic and preparations","Anti-horse-fly oils","Anti-incrustants","Anti-interference devices",
            "Anti-knock substances for internal combustion engines","Anti-leptospiral seras","anti-monopoly act","Anti-pollution devices for motors and engines","anti-rebating",
            "anti-rebating law","Anti-rheumatism bracelets","Anti-rheumatism rings","Anti-rolling tank type stabilizers","Anti-rust greases",]
        
        ReturnWordArray += wordStore
        
        return ReturnWordArray
        
    }
   
}
